### ISSUE TITLE
cant start master because of some random image generation 

### ISSUE THREAD

**Issue by kikass13** [protontypes/libreselery#128]
```
 ./run.sh ~/gitclones/openselery
=======================================================
[*] Initializing OpenSelery
[.] OpenSelery version [dev-packageificationize.dev119]
[.] Preparing Configuration
[.] Loading configurations
 -- /home/selery/runningrepo/selery.yml
[.] Using bitcoin address from configuration file for validation check [3PVdiyLPR7MgaeFRJLW9mfuESZS2aAPX9w]
[.] Creating QR code PNG image for funders
Traceback (most recent call last):
  File "/usr/local/bin/selery", line 4, in <module>
    __import__('pkg_resources').run_script('openselery===dev-packageificationize.dev119', 'selery')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/site-packages/openselery-dev_packageificationize.dev119-py3.7.egg/EGG-INFO/scripts/selery", line 6, in <module>
    runCli()
  File "/usr/local/lib/python3.7/site-packages/openselery-dev_packageificationize.dev119-py3.7.egg/openselery/commandline.py", line 10, in runCli
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/openselery-dev_packageificationize.dev119-py3.7.egg/openselery/commandline.py", line 20, in _runCommand
    selery = openselery.OpenSelery(config)
  File "/usr/local/lib/python3.7/site-packages/openselery-dev_packageificationize.dev119-py3.7.egg/openselery/openselery.py", line 34, in __init__
    self.initialize()
  File "/usr/local/lib/python3.7/site-packages/openselery-dev_packageificationize.dev119-py3.7.egg/openselery/openselery.py", line 108, in initialize
    os.path.join(self.config.result_dir, "public", "wallet_qrcode.png")
  File "/usr/local/lib/python3.7/site-packages/qrcode-6.1-py3.7.egg/qrcode/image/pil.py", line 50, in save
    self._img.save(stream, format=format, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/Pillow-7.2.0-py3.7-linux-x86_64.egg/PIL/Image.py", line 2155, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/home/selery/results/public/wallet_qrcode.png'
[*] Feel free to visit us @ https://github.com/protontypes/openselery
=======================================================
 ```

**Comment by Ly0n** [comment]
We added another sub-folder called "public" in results to distinguish between public and private date since the transaction.txt contains many private email address and the content of the wiki is public to every one without an Github account. @kikass13 all ready told me that it might be better to create the folder with the run.sh script.

**Comment by Ly0n** [comment]
README is changed to add public folder
